version: '3.7'
services:

  db:
    image: postgres:12.6-alpine
    container_name: db
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./postgres_scripts:/root/postgres_scripts/

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    command: redis-server --bind redis --appendonly yes
    volumes:
      - ./redis_scripts/sysctl.conf:/etc/sysctl.conf
    sysctls:
      net.core.somaxconn: "4096"


  app:
    build: .
    image: app-image
    container_name: app
    command: sh -c "python manage.py migrate &&
                    python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db

  celery:
    image: app-image
    container_name: celery_worker
    command: ['celery', '-A', 'timespick', 'worker', '--loglevel=INFO', '--broker=redis://redis:6379']
    volumes:
      - .:/code
    depends_on:
      - app
      - redis

  flower:
    build: .
    image: app-image
    container_name: flower
    command: celery flower -A timespick -loglevel=INFO --broker=redis://redis:6379 --port=5555
    volumes:
      - .:/code
    ports:
      - 5555:5555
    depends_on:
      - app
      - redis
      - celery

volumes:
  postgres_data:

