# Generated by Django 3.1.1 on 2020-09-11 10:20

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('phone', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_service', models.BooleanField(default=False)),
                ('dates', django.contrib.postgres.fields.ArrayField(base_field=models.DateField(), blank=True, null=True, size=None)),
                ('title', models.CharField(blank=True, max_length=64)),
                ('money', models.IntegerField(null=True)),
                ('info', models.TextField(blank=True)),
                ('client', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.client')),
            ],
        ),
    ]
