# Generated by Django 3.1.1 on 2020-09-14 10:55

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200911_1046'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDayOff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dayoff', django.contrib.postgres.fields.ArrayField(base_field=models.DateField(), blank=True, null=True, size=None)),
            ],
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-is_service']},
        ),
    ]
