# Generated by Django 3.1.1 on 2020-09-14 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200914_1117'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdaysoff',
            old_name='dayoff',
            new_name='daysoff',
        ),
    ]
