# Generated by Django 3.1.1 on 2020-09-15 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20200914_1134'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdaysoff',
            old_name='daysoff',
            new_name='days_off',
        ),
    ]
