# Generated by Django 3.1.1 on 2020-09-29 18:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0013_auto_20200929_0406'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Client',
            new_name='Contact',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='client',
            new_name='contact',
        ),
    ]
