# Generated by Django 3.1.1 on 2020-10-03 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20201003_0918'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
