# Generated by Django 3.1.1 on 2020-10-14 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20201003_0919'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='client',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
    ]
