# Generated by Django 3.1.1 on 2020-10-14 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_project_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='contact',
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
