# Generated by Django 3.1.1 on 2020-10-25 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_userprofile_is_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
