# Generated by Django 3.1.1 on 2020-11-12 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_project_is_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='date_end',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='date_start',
            field=models.DateField(null=True),
        ),
    ]
