# Generated by Django 3.1.1 on 2020-11-29 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_auto_20201129_2352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='day',
            name='user',
        ),
    ]
