# Generated by Django 3.1.1 on 2021-01-01 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_auto_20210101_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='clientModel',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.client'),
        ),
    ]
