# Generated by Django 3.1.1 on 2021-01-01 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_project_clientmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='client',
        ),
    ]
