# Generated by Django 3.1.1 on 2021-01-01 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_remove_project_client'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='clientModel',
            new_name='client',
        ),
    ]
