# Generated by Django 3.1.1 on 2021-02-07 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_auto_20210207_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='days', to='api.project'),
        ),
    ]
