# Generated by Django 3.1.1 on 2021-02-08 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_project_money_per_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='money_calculating',
            field=models.BooleanField(default=False),
        ),
    ]
