# Generated by Django 3.1.1 on 2021-02-09 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_auto_20210209_1524'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='user',
        ),
        migrations.RemoveField(
            model_name='project',
            name='user',
        ),
    ]
