# Generated by Django 3.1.1 on 2021-02-09 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_auto_20210209_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='creator_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_projects', to='api.userprofile'),
        ),
    ]
