# Generated by Django 3.1.1 on 2021-02-09 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_project_creator_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='creator',
        ),
    ]
