# Generated by Django 3.1.1 on 2021-02-09 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_remove_project_creator'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='creator_profile',
            new_name='creator',
        ),
    ]
