# Generated by Django 3.1.1 on 2021-02-15 10:02

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_auto_20210215_1001'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='userprofile',
            managers=[
                ('clients', django.db.models.manager.Manager()),
            ],
        ),
    ]
