# Generated by Django 3.1.1 on 2021-02-16 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_auto_20210215_1416'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='position',
            options={'ordering': ['title']},
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='positions',
            field=models.ManyToManyField(related_name='profiles', to='api.Position'),
        ),
    ]
