# Generated by Django 3.1.1 on 2021-02-17 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_auto_20210216_2005'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email_confirm',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone_confirm',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
