# Generated by Django 3.1.1 on 2021-02-17 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_auto_20210217_0914'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='is_confirmed',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='email_confirm',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone_confirm',
            field=models.BooleanField(default=False),
        ),
    ]
