# Generated by Django 3.1.1 on 2021-02-17 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0054_auto_20210217_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='positions',
            field=models.ManyToManyField(blank=True, null=True, related_name='profiles', to='api.Position'),
        ),
    ]
