# Generated by Django 3.1.1 on 2021-02-17 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0058_userprofile_telegram_chat_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegram',
            name='chat_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='telegram',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='telegram_phone_confirm', to='api.userprofile'),
        ),
    ]
