# Generated by Django 3.1.1 on 2021-02-17 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0059_auto_20210217_2059'),
    ]

    operations = [
        migrations.RenameField(
            model_name='telegram',
            old_name='user',
            new_name='profile',
        ),
    ]
