# Generated by Django 3.1.1 on 2021-02-18 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0060_auto_20210217_2103'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Telegram',
        ),
    ]
