# Generated by Django 3.1.1 on 2021-02-26 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0067_auto_20210226_0659'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='tags',
        ),
    ]
