# Generated by Django 3.1.1 on 2021-02-26 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0069_auto_20210226_0837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='custom',
            field=models.BooleanField(default=True),
        ),
    ]
