# Generated by Django 3.1.1 on 2021-02-27 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0071_tag_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiletag',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='api.userprofile'),
        ),
    ]
