# Generated by Django 3.1.1 on 2021-02-27 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0073_auto_20210227_1309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='positions',
        ),
        migrations.DeleteModel(
            name='Position',
        ),
    ]
