# Generated by Django 3.1.1 on 2021-02-28 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0074_auto_20210227_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_wait',
            field=models.BooleanField(default=False),
        ),
    ]
