# Generated by Django 3.1.1 on 2021-03-16 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0076_userprofile_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='show_email',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='show_phone',
            field=models.BooleanField(default=True),
        ),
    ]
