# Generated by Django 3.1.1 on 2021-03-22 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0080_userprofile_facebook_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='facebook_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='telegram_chat_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
