# Generated by Django 3.1.1 on 2021-03-22 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0081_auto_20210322_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='facebook_id',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
