# Generated by Django 3.1.1 on 2021-03-22 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0082_auto_20210322_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='email_confirm',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone_confirm',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
    ]
