# Generated by Django 3.1.1 on 2021-03-23 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0085_userprofile_facebook_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='facebook_id',
        ),
    ]
