# Generated by Django 3.1.1 on 2021-03-23 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0086_remove_userprofile_facebook_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='facebook_account',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile', to='api.facebookaccount'),
        ),
    ]
