# Generated by Django 3.1.1 on 2021-04-06 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0088_auto_20210324_1017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='category',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='custom',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='info',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='level',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='lft',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='rght',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='tree_id',
        ),
    ]
