# Generated by Django 3.1.1 on 2021-04-18 07:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0090_userprofile_last_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='last_activity',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 18, 7, 46, 13, 97667, tzinfo=utc)),
        ),
    ]
