# Generated by Django 3.1.1 on 2021-04-18 07:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0091_auto_20210418_0746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='last_activity',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
