# Generated by Django 3.1.1 on 2021-05-08 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0092_auto_20210418_0752'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='canceled',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='canceled_projects', to='api.userprofile'),
        ),
        migrations.AddField(
            model_name='project',
            name='confirmed',
            field=models.BooleanField(default=True),
        ),
    ]
