# Generated by Django 3.1.1 on 2021-05-08 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0094_auto_20210508_2007'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='last_activity',
            new_name='raised',
        ),
    ]
