# Generated by Django 3.1.1 on 2021-07-31 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0097_auto_20210601_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='default',
            field=models.BooleanField(default=False),
        ),
    ]
