# Generated by Django 3.1.1 on 2021-08-06 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0100_contacts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='money_per_day',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
