# Generated by Django 3.1.1 on 2021-08-07 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0101_auto_20210806_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
