# Generated by Django 3.1.1 on 2021-08-16 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0103_projectresponse'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectresponse',
            options={'ordering': ['project', 'time']},
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=64, null=True)),
                ('last_name', models.CharField(blank=True, max_length=64, null=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=32, null=True)),
                ('telegram', models.CharField(blank=True, max_length=32, null=True)),
                ('info', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile', to='api.userprofile')),
            ],
        ),
    ]
