# Generated by Django 3.1.1 on 2021-08-16 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0105_auto_20210816_0902'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiletag',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='api.profile'),
        ),
    ]
