# Generated by Django 3.1.1 on 2021-08-16 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0107_auto_20210816_0921'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user',
            new_name='account',
        ),
    ]
