# Generated by Django 3.1.1 on 2021-08-16 12:26

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0108_auto_20210816_1202'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Account',
            new_name='UserProfile',
        ),
    ]
