# Generated by Django 3.1.1 on 2021-08-16 12:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('api', '0109_auto_20210816_1226'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='account', serialize=False, to='auth.user')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('email_confirm', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('phone', models.CharField(blank=True, max_length=32, null=True)),
                ('phone_confirm', models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ('telegram_chat_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('is_public', models.BooleanField(default=False)),
                ('raised', models.DateTimeField(default=django.utils.timezone.now)),
                ('facebook_account', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account', to='api.facebookaccount')),
            ],
        ),
    ]
