# Generated by Django 3.1.1 on 2021-08-16 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0110_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiletag',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='api.userprofile'),
        ),
    ]
