# Generated by Django 3.1.1 on 2021-08-16 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0111_profiletag_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profiletag',
            options={'ordering': ['user', 'rank']},
        ),
        migrations.RemoveField(
            model_name='profiletag',
            name='profile',
        ),
    ]
