# Generated by Django 3.1.1 on 2021-08-16 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0112_auto_20210816_1254'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
