# Generated by Django 3.1.1 on 2021-08-17 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0114_userprofile_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='email_confirm',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='facebook_account',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='is_public',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='phone_confirm',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='raised',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='show_email',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='show_phone',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='telegram_chat_id',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='telegram',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
