# Generated by Django 3.1.1 on 2021-08-30 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0115_auto_20210817_0917'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contacts',
        ),
    ]
