# Generated by Django 3.1.1 on 2021-09-27 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0117_project_is_series'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='favorites',
            field=models.ManyToManyField(related_name='favorite_of', to='api.UserProfile'),
        ),
    ]
