# Generated by Django 3.1.1 on 2021-10-01 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0119_account_telegram_notifications'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectShowing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.BooleanField(default=False)),
                ('comment', models.TextField(blank=True, null=True)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='api.project')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='api.userprofile')),
            ],
            options={
                'ordering': ['project', 'time'],
            },
        ),
        migrations.AlterField(
            model_name='account',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='favorite_of', to='api.UserProfile'),
        ),
        migrations.DeleteModel(
            name='ProjectResponse',
        ),
    ]
